#!/usr/bin/env bash
# Copy windows/*.ps1 to the instance over SSM and run setup.ps1 with secrets
# pulled from EC2/Keychain. Usage: ./bootstrap.sh <instance-id>
set -euo pipefail

export AWS_PROFILE=${AWS_PROFILE:-m5mbp}
export AWS_REGION=${AWS_REGION:-us-east-1}
IID=${1:?usage: bootstrap.sh <instance-id>}
here=$(cd "$(dirname "$0")" && pwd)

# Windows password: generated by EC2, decrypted with the launch key
WINPW=$(aws ec2 get-password-data --instance-id "$IID" --priv-launch-key ~/.ssh/cloud-gaming.pem \
  --query PasswordData --output text)
security add-generic-password -U -a Administrator -s gaming-pc-windows -w "$WINPW"

# Apollo web UI password: reuse the Keychain one, or make a new one
if ! APW=$(security find-generic-password -s gaming-pc-apollo-ui -w 2>/dev/null); then
  APW=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)
  security add-generic-password -U -a admin -s gaming-pc-apollo-ui -w "$APW"
fi

# Ship the scripts base64-encoded inside the SSM command, then run setup.ps1.
# Secrets are passed as arguments, so they appear in this account's SSM command history.
cmds=$(python3 - "$here" "$APW" "$WINPW" <<'EOF'
import base64, json, pathlib, sys
here, apw, winpw = sys.argv[1:]
lines = ["New-Item -ItemType Directory -Force C:\\gaming\\repo | Out-Null"]
for f in ("setup.ps1", "idle.ps1"):
    b64 = base64.b64encode(pathlib.Path(here, "windows", f).read_bytes()).decode()
    lines.append(f"[IO.File]::WriteAllBytes('C:\\gaming\\repo\\{f}', [Convert]::FromBase64String('{b64}'))")
lines.append(f"& C:\\gaming\\repo\\setup.ps1 -ApolloPassword '{apw}' -WindowsPassword '{winpw}'")
print(json.dumps({"commands": lines, "executionTimeout": ["3600"]}))
EOF
)
CID=$(aws ssm send-command --instance-ids "$IID" --document-name AWS-RunPowerShellScript \
  --parameters "$cmds" --timeout-seconds 600 --query Command.CommandId --output text)
echo "SSM command $CID running (takes ~15 min, ends with a reboot)"
until s=$(aws ssm get-command-invocation --command-id "$CID" --instance-id "$IID" --query Status --output text 2>/dev/null) &&
  [[ $s != InProgress && $s != Pending ]]; do sleep 20; done
echo "Status: $s"
aws ssm get-command-invocation --command-id "$CID" --instance-id "$IID" --query StandardOutputContent --output text | tail -5
